name: CI

on: push

jobs:
  format:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Packages
        run: yarn
      - name: Check Format
        run: yarn test:format

  build:
    name: Build portfolio
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Use Node.js 14
       uses: actions/setup-node@v1
       with:
         node-version: 14
     - name: Install Packages
       run: yarn
     - name: Deploy to GH Pages
       run: yarn deploy
